### ISSUE TITLE
Make hyperas run inside iPython notebook

### ISSUE THREAD

**Issue by lishen** [maxpumperla/hyperas#31]
This is a suggestion to enhance hyperas so that it can be used within iPython notebook. This enhancement is also related to issue: #28 

In current implementation, hyperas tries to read the "import" lines from its calling script and write them to an external temporary file. This does not work with an iPython notebook because those "import" lines are modified by the notebook. I could not figure out a quick-and-easy solution to it. It may require some redesign of the running mechanisms of hyperas. @maxpumperla

**Comment by maxpumperla** [comment]
Yes, thanks. I'm aware of the situation. Right now I don't have a great idea on how to fix this without doing something really awkward. Actually, I hope to rewrite hyperas at some point to resolve this. If you have a concrete suggestion, let me know.

**Comment by sohan** [comment]
Hey @lishen and @maxpumperla, I was able to get hyperas working well inside of an iPython notebook. I just had to copy all my imports into my `data()` function as the docs suggest. I also applied #34, which fixes a bug where multiline comments with the word "import" get inlined into the template.

**Comment by maxpumperla** [comment]
Hey @lishen and @sohan, we now support notebooks. See the example folder. I need to update the documentation accordingly (note the `notebook_name` parameter that's needed, since it's very complicated to inspect the name of the notebook you're working in). Feedback welcome! Thanks

**Comment by ErmiaAzarkhalili** [comment]
@maxpumperla @lishen @sohan 
Unfortunately does not work on pycharm 2016.3. 
get the fiollowing error:

Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/IPython/core/interactiveshell.py", line 2881, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-6-4027738f0d4a>", line 75, in <module>
    notebook_name='simple_notebook')
TypeError: minimize() got an unexpected keyword argument 'notebook_name'

which shows that it cannot utilized the new argument "notebook_name" inside "optimi.minimize" function.

**Comment by maxpumperla** [comment]
@ErmiaAzarkhalili to me that looks like you didn't install the latest master first. This is a new keyword not available in previous versions. Once this proves to work, I'll release a new version.

**Comment by ErmiaAzarkhalili** [comment]
@maxpumperla how did you do this step personally? I cloned and reinstalled both hyperopt and hyperas, but something went wrong.
I know that it's new keyword, but seems as if something is wrong.

**Comment by simahgh** [comment]
Hello everyone, 
I am trying to use this package, but when I am trying to run my code on jupyter python, it gives different errors of invalid syntax, I am wondering if you could help me.


`
```
def data():
    mat = loadmat('C:/Users/simah/Downloads/Kaneshiro_etAl_objectCategoryEEG/Kaneshiro_etAl_objectCategoryEEG/S1.mat')  # load mat-file matX1=loadmat('C:/Users/simah/Downloads/Kaneshiro_etAl_objectCategoryEEG/Kaneshiro_etAl_objectCategoryEEG/XL1.mat') 
    
    X11=matX1['XL1']
    Y11=mat['categoryLabels']
    enc = preprocessing.OneHotEncoder()
    enc.fit(Yd)
    Y=enc.transform(Yd).toarray()
    Xx=np.vstack((X11,X21,X31,X41,X51))
    train_X, test_X, train_y, test_y=train_test_split(Xx,Y, test_size=0.3)
    return train_X, test_X, train_y, test_y

```




```
def model(train_X, test_X, train_y, test_y):
    timesteps = 32
    input_dim = 124
    num_classes = 6 
    model = Sequential()
    model.add(LSTM({{choice([256, 120, 80])}}, input_shape=(timesteps, input_dim), return_sequences=True,  activation='tanh'))
    model.add(Dropout({{uniform(0, 1)}}))
    model.add(LSTM(96,activation='tanh',dropout=0.2))
    model.add(Dense(num_classes, activation="softmax"))
    model.compile(loss='categorical_crossentropy', optimizer={{choice(['rmsprop', 'adam', 'sgd'])}})
    model.fit(train_X, train_y,batch_size={{choice([64, 128])}},nb_epoch={{choice([10, 20])}},show_accuracy=True,verbose=0,validation_data=(X_test, Y_test))
    score, acc = model.evaluate(test_X, test_y, show_accuracy=True, verbose=0)
    print('Test accuracy:', acc)
    return {'loss': -acc, 'status': STATUS_OK, 'model': model}

```
```
if __name__ == '__main__':

    train_X, test_X, train_y, test_y = data()
    best_run, best_model = optim.minimize(model=model,data=data,algo=tpe.suggest,max_evals=5,trials=Trials(),notebook_name='simple_notebook2')
    print("Evalutation of best performing model:")
    print(best_model.evaluate(test_X, test_y))
`
```

**Comment by 648374hub** [comment]
Hello sir,
Is there a way to use hyperas with jupyter notebook or spider, because I'm facing the same issues like others and also when I pass the 'notebook_name' argument, an error occurred stating, 'list index out of range'.?
